import {j as e,L as Link} from '../assets/vendor-core-CjvpFyCc.js';
const content={
 privacy:{title:'Privacy Policy',sections:[['About this version','This is a separately hosted, payment-free recreation of the Wishprise frontend. It is not connected to the original website’s account, payment or storage services.'],['Content you share','Names, messages, cake settings, photos and voice notes are stored in this project’s Table API. These tables do not implement per-record authorization. Random share links are convenient identifiers, not access controls. Do not upload confidential or sensitive content.'],['Retention and deletion','Automatic expiry and scheduled deletion are not implemented. Content remains until the project owner removes it. The operator can manage records from the project’s Data tab.'],['Browser features','Microphone permission is requested only for recording or candle interaction. Poster images are processed in your browser. Google Fonts and selected public image hosts receive normal browser requests. Original-site analytics, advertisements, API credentials and checkout scripts are not included.'],['Before public use','The project owner must configure their own contact address, retention policy and server-enforced record permissions before accepting private visitor data.']]},
 terms:{title:'Terms of Service',sections:[['A payment-free recreation','This version provides interactive birthday experiences without checkout, subscriptions or purchases. It is a frontend recreation, not a connection to the original Wishprise business.'],['Your content','Only upload material you have permission to share. Avoid sensitive personal data. Project tables are not private-record storage.'],['Feature availability','The birthday experience, free share links, poster studio and template wishes run in this version. AI generation is not connected. NASA results open on the official public archive rather than through an authenticated API.'],['No retention guarantee','There is no scheduled deletion or guaranteed availability period. Please retain your own copies of important photos and messages.']]},
 cookies:{title:'Cookies & Browser Storage',sections:[['Browser preferences','The interface may save language and consent preferences in local storage. You can clear these through your browser’s site settings.'],['No original tracking','This recreation does not include the original site’s advertising or analytics scripts. Google Fonts and external image hosts are still used for presentation.'],['Permission controls','You can refuse or revoke microphone access through browser settings. Sharing and poster downloads occur only after you choose those actions.']]},
 contact:{title:'Contact & Support',sections:[['Project support','A support email has not yet been configured for this recreation. Please contact the person who shared this project with you. This version does not send messages to the original Wishprise team.'],['Having trouble opening a surprise?','Check that you are using the complete link on the same public website where it was created. Preview data and a Hosted Deploy database are separate.'],['Microphone and audio','Allow microphone permission when prompted and interact with the page to enable audio. Microphone features require HTTPS or localhost.'],['For the project owner','Configure a support address and privacy contact before public launch. Use the Data tab to manage stored surprises and feedback.']]},
 pricing:{title:'A little magic. No payment.',sections:[['Create and share for free','Personalize your cake, write your message, add optional media and get a shareable link. There is no payment page, card collection or checkout in this version.'],['What is included','Interactive birthday experience, cake customization, wish wheel, personal messages, photos, voice notes, poster studio and template-based birthday wishes.'],['Know what you share','Project tables do not implement private-record authorization or automatic expiry. Only share non-sensitive content.']]},
 refunds:{title:'No payments. No refunds needed.',sections:[['Payment-free version','This recreation does not process any payments, collect card information or create paid orders.'],['Original-site purchases','We cannot access purchases, receipts or refunds belonging to the original website. Contact the original merchant directly for any unrelated transaction.'],['Digital delivery','Your link becomes available when your content is successfully saved. A failed save displays an error rather than sending you to a checkout.']]},
 delivery:{title:'Digital Delivery',sections:[['A link, not a parcel','This experience is entirely digital. After saving your surprise, copy its link or share it through WhatsApp. No physical products are shipped.'],['No payment required','The share page is available immediately after a successful save. Your recipient can open the link in a modern browser.'],['Where your data lives','Links work against the data store of the website where they were created. Preview and Hosted Deploy data are independent. Links do not automatically expire.']]}
};
export function PolicyPage({type}){const page=content[type];return e.jsxs('div',{className:'wp-policy',children:[e.jsxs('header',{children:[e.jsx(Link,{to:'/',children:e.jsx('img',{src:(window.__WP_BASE__||'/')+'logo.png',alt:'Wishprise'})}),e.jsx(Link,{to:'/',children:'← Back to home'})]}),e.jsxs('main',{children:[e.jsx('h1',{children:page.title}),...page.sections.map(([title,text])=>e.jsxs('section',{children:[e.jsx('h2',{children:title}),e.jsx('p',{children:text})]},title)),e.jsx(Link,{to:'/create',className:'wp-primary',children:'Create my surprise →'})]})]});}
